name: Privacy, Security, & Infrastructure Readiness Review [Team-Name, Feature-Name]
description: Request a Privacy, Security, & Infrastructure Readiness Review.
title: "Readiness Review [Team-Name, Feature-Name]"
labels: ["security-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Define Phase
  - type: markdown
    attributes:
      value: |
        Text
  - type: markdown
    attributes:
      value: |
          ### General
  - type: checkboxes
    id: general-documentation
    attributes:
      label: Please review the following documentation prior to completing this questionnaire.
      description: More text
      options:
        - label: The team has reviewed the documentation provided.
          required: true
  - type: markdown
    attributes:
      value: |
          ### Hosting Environment
  - type: checkboxes
    id: hosting-outside
    attributes:
      label: Please check the appropriate box if any of the following statements are True.
      options:
        - label: This feature will connect to an endpoint developed by the VFS team and hosted outside of the VFS Platform.
  - type: markdown
    attributes:
      value: |
          If your team checked any of the boxes above, please answer the following questions to the best of your knowledge.
          - Please provide information for the hosting environment and location, for example, the VAEC cloud.
  - type: textarea
    id: hosting-details
    attributes:
      label: Details
  - type: markdown
    attributes:
      value: |
          ### External Connections
  - type: checkboxes
    id: external-data
    attributes:
      label: Please check the appropriate box if any of the following statements are True.
      options:
        - label: This feature shares data or other information resources with the VA, VA Partner, or a third party.
  - type: markdown
    attributes:
      value: |
         Responses
         If your team checked any of the boxes above, please answer the following questions to the best of your knowledge.
          - Please summarize the need for the external connection.
          - Please provide the name, function, and location of the external connection.
          - Please describe the data or information exchanged using the external connection.

         Guidelines
          - External Connections that share data or other information resources with any system that has a different Authorizing Official (AO) require a Memorandum of Understanding (MOU) / Interconnection Security Agreement (ISA) agreement completed before the connection can be turned up.
          - External Connections must traverse the forward proxy.
  - type: textarea
    id: external-details
    attributes:
      label: Details
