name: Privacy, Security, & Infrastructure Readiness Review [Team-Name, Feature-Name]
description: Request a Privacy, Security, & Infrastructure Readiness Review.
title: "Readiness Review [Team-Name, Feature-Name]"
labels: ["security-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Guidance
  - type: markdown
    attributes:
      value: |
        - VFS Lead engineer or product manager: using this template, create issue in `va.gov-team-sensitive` and answer the questionnaire in its entirety.
        - Do _**NOT**_ put any PII, PHI, or other Potentially Sensitive Data into the Issue contents.
        - Notify the Platform Security Team of this request in the #vfs-platform-support Slack channel upon filing.
        - The Platform Security Team will review this issue and **conduct all conversations and follow-ups through this issue** (**ex**cluding PII/PHI/Potentially Sensitive Data).
            - As a requester: complete any follow-up action items and provide all requested information in this issue.
        - Do _**NOT**_ close this issue, Security Reviews may only be closed by a member of the Platform Security Team. The Platform Security Team will update the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) upon closure.
  - type: markdown
    attributes:
      value: |
        ## Team/Product Information
  - type: input
    id: lead-eng
    attributes:
      label: Lead engineer
    validations:
      required: true
  - type: input
    id: pm
    attributes:
      label: Product manager
    validations:
      required: true
  - type: input
    id: prod-lead
    attributes:
      label: OCTO-DE product lead
    validations:
      required: true
  - type: input
    id: anyone-else
    attributes:
      label: Anyone else on your team whose presence is needed to speak to the technical architecture and security concerns
  - type: input
    id: product-outline
    attributes:
      label: Link to product outline
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Define Phase
  - type: markdown
    attributes:
      value: |
        This questionnaire gathers relevant security information from the Veteran Facing Services (VFS) application team and provides some security guidance and information to help prepare for the Privacy and Security Review.
  - type: markdown
    attributes:
      value: |
          ### General
  - type: checkboxes
    id: general-documentation
    attributes:
      label: Please review the following documentation prior to completing this questionnaire.
      description: More text
      options:
        - label: The team has reviewed the documentation provided.
          required: true
  - type: markdown
    attributes:
      value: |
          ### Hosting Environment
  - type: checkboxes
    id: hosting-outside
    attributes:
      label: Please check the appropriate box if any of the following statements are True.
      options:
        - label: This feature will connect to an endpoint developed by the VFS team and hosted outside of the VFS Platform.
  - type: markdown
    attributes:
      value: |
          If your team checked any of the boxes above, please answer the following questions to the best of your knowledge.
          - Please provide information for the hosting environment and location, for example, the VAEC cloud.
  - type: textarea
    id: hosting-details
    attributes:
      label: Details
  - type: markdown
    attributes:
      value: |
          ### External Connections
  - type: checkboxes
    id: external-data
    attributes:
      label: Please check the appropriate box if any of the following statements are True.
      options:
        - label: This feature shares data or other information resources with the VA, VA Partner, or a third party.
  - type: markdown
    attributes:
      value: |
         Responses
         If your team checked any of the boxes above, please answer the following questions to the best of your knowledge.
          - Please summarize the need for the external connection.
          - Please provide the name, function, and location of the external connection.
          - Please describe the data or information exchanged using the external connection.

         Guidelines
          - External Connections that share data or other information resources with any system that has a different Authorizing Official (AO) require a Memorandum of Understanding (MOU) / Interconnection Security Agreement (ISA) agreement completed before the connection can be turned up.
          - External Connections must traverse the forward proxy.
  - type: textarea
    id: external-details
    attributes:
      label: Details
  - type: markdown
    attributes:
      value: |
          ### Source Code
  - type: checkboxes
    id: source-stuff
    attributes:
      label: Please check the appropriate box if any of the following statements are True.
      options:
        - label: This feature includes an update to the `vets-api` source code.
        - label: This feature includes an update to the `vets-website` source code.
        - label: This feature includes an update to some other source code on the VFS Platform.
        - label: This feature does not include an update on the VFS Platform.
  - type: markdown
    attributes:
      value: |
         Responses
          If your team checked any of the boxes above, please answer the following questions to the best of your knowledge.
          - Please provide a link to any source code repositories.
          - Please provide a list of resources that will have write access to a repository and the repository name.
          - Please provide an estimate for the duration of the project.
          - Please describe any updates to be included and where those updates are necessary.
          - Please describe the code development and code review process that will be used.
  - type: textarea
    id: source-details
    attributes:
      label: Details
  - type: markdown
    attributes:
      value: |
          ### Privacy
  - type: checkboxes
    id: privacy-stuff
    attributes:
      label: Please check the appropriate box if any of the following statements are True.
      options:
        - label: This feature uses Personal Identifiable Information (PII).
        - label: This feature uses Personal Health Information (PHI).
        - label: This feature uses Personal Information (PI).
  - type: markdown
    attributes:
      value: |
         Responses
         If your team checked any of the boxes above, please answer the following questions to the best of your knowledge.
         - Please summarize the need for the PHI, PII, or PI.
         - Please describe the PHI, PII, or PI used by the feature.
         
         Guidelines
         - Personal Information (PI) should be removed whenever possible.
         - Personal Health Information (PHI) and Personal Identifiable Information (PII) must be encrypted.
  - type: textarea
    id: privacy-details
    attributes:
      label: Details
  - type: markdown
    attributes:
      value: |
        ## Build Phase
  - type: markdown
    attributes:
      value: |
        Please review and use the following documentation examples as you develop the feature. This will ensure consistency and help speed up the review process.
        - Feature Architecture Diagram – Example
        - Feature Sequence Diagram – Example
        - Feature Data Flow Diagram – Example
        - Feature API Endpoint Documentation – Example
        - Feature Playbook – Example
        
        Provide completed documentation as you build your feature.
  - type: input
    id: architecture-diagram
    attributes:
      label: Architecture diagram
  - type: input
    id: incident-response-plan
    attributes:
      label: Incident response plan
  - type: input
    id: sequence-diagram
    attributes:
      label: Sequence diagram
  - type: input
    id: data-flow-diagram
    attributes:
      label: Data flow diagram
  - type: input
    id: api-endpoint-docs
    attributes:
      label: API endpoint documentation
