name: Privacy, Security, & Infrastructure Readiness Review [Team-Name, Feature-Name]
description: Request a Privacy, Security, & Infrastructure Readiness Review.
title: "Readiness Review [Team-Name, Feature-Name]"
labels: ["security-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Define Phase
  - type: markdown
    attributes:
      value: |
        Text
  - type: markdown
    attributes:
      value: |
          ### General
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: What kinds of cats do you like?
      description: You may select more than one.
      options:
        - label: Orange cat (required. Everyone likes orange cats.)
          required: true
