name: Privacy, Security, & Infrastructure Readiness Review [Team-Name, Feature-Name]
description: Request a Privacy, Security, & Infrastructure Readiness Review.
title: "Readiness Review [Team-Name, Feature-Name]"
labels: ["security-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Define Phase
  - type: markdown
    attributes:
      value: |
        Text
  - type: markdown
    attributes:
      value: |
          ### General
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: Please review the following documentation prior to completing this questionnaire.
      description: More text
      options:
        - label: The team has reviewed the documentation provided.
          required: true
